### ISSUE TITLE
Using Fixture Adapter Conditionally

### ISSUE THREAD

**Issue by ronco** [cristinawithout/ember-cli-data-factory-guy#9]
We only want to use the fixture adapter with our acceptance tests some of the time.  The rest of the time we want to use our apps real adapter and mock the http API responses.  This worked when our app was using Globals, but converting to an ember-cli app we could no longer conditionally override it.

I was able to fix this by initializing the acceptance app with a this custom resolver:

```javascript
// 'tests/helpers/fixture-resolver'
import Resolver from 'ember/resolver';
import DS from 'ember-data';

var FixtureResolver = Resolver.extend({
  resolveOther: function(parsedName) {
    if (parsedName.type !== 'adapter') {
      return this._super(parsedName);
    }
    return DS.FixtureAdapter;
  }

});

export default FixtureResolver;
```

Then in start-app.js:
```javascript
  if (attributes.usingFixtures) {
    attributes.Resolver = fixtureResolver;
  }
  Ember.run(function() {
    application = Application.create(attributes);
    application.setupForTesting();
    application.injectTestHelpers();
  });
```

It would be great if this add-on provided this (or a better solution).

**Comment by danielspaniel** [comment]
Taking a look at this in the next few days.

**Comment by cristinawithout** [comment]
Daniel, do you need this issue open or is it something that's been fixed in ember-data-factory-guy?

**Comment by danielspaniel** [comment]
Hmm .. this is good question .. and when I switched to ember-data-factory-guy being an add on .. I dropped support for FixtureAdapter ( populate fixture data with factory guy ) 
.. but with this solution you can use the fixture adapter outside of factory guy as you suggest, and do your own fixtures?? 
  And if you can come up with a better solution .. let me know .. ( write me a hint ) .. or submit PR 
 and I can get that included in ember-data-factory-guy .. 
 since this ember-cli-factory-guy package is deprecated.

 I am curious for the use case for this .. why use FixtureAdapter sometimes and then real adapter .. me curious?
